import type { Metadata } from "next";
import { createServiceClient } from "@/lib/supabase/service";
import { notFound } from "next/navigation";
import Link from "next/link";
import JsonLd from "@/app/components/JsonLd";
import { buildPageMetadata, toAbsoluteUrl } from "@/lib/seo";
import { MarketingShell } from "@/components/ui/MarketingShell";
import { Card } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { DescriptionList } from "@/components/ui/DescriptionList";
import { BreakdownList } from "@/components/ui/BreakdownList";
import { SharePagePrintButton } from "./SharePagePrintButton";
import "./shared-settlement.css";

/**
 * Public share page for settlements
 * Typography matches rest of app: --text-2xl (page title), --text-sm (section titles), --text-base (values), --text-lg (highlight row).
 * Server component that fetches show data using service role to bypass RLS
 * No authentication required - access granted via valid active token
 */

interface Show {
  id: string;
  user_id: string;
  title: string | null;
  show_date: string | null;
  inputs: {
    artistName?: string;
    ticketTiers?: { name: string; price: string; sold: string; comps?: string }[];
    capacity?: string;
    ticketPrice?: string;
    ticketsSold?: string;
    taxRate?: string;
    totalExpenses?: string;
    expenseItems?: { label: string; amount: string }[];
    dealType?: string;
    guarantee?: string;
    percentage?: string;
  };
  results: {
    grossRevenue: number;
    ticketTiers?: { name: string; price: number; sold: number; comps: number; revenue: number }[];
    totalTicketsSold?: number;
    totalComps?: number;
    taxAmount: number;
    totalExpenses: number;
    expenseItems?: { label: string; amount: number }[];
    netProfit: number;
    artistPayout: number;
    venuePayout: number;
  };
  created_at: string;
  updated_at: string;
}

export async function generateMetadata(): Promise<Metadata> {
  return buildPageMetadata({
    title: "Shared Settlement - GigSettle",
    description: "View a shared settlement packet generated by GigSettle.",
    path: "/s",
    noIndex: true,
  });
}

/**
 * Formats a number as USD currency
 */
function formatCurrency(amount: number): string {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return formatter.format(amount);
}

/**
 * Formats deal type for display
 */
function formatDealType(dealType: string): string {
  switch (dealType) {
    case "guarantee":
      return "Guarantee";
    case "percentage":
      return "Percentage of Net";
    case "guarantee_vs_percentage":
      return "Guarantee vs Percentage (whichever is higher)";
    default:
      return dealType;
  }
}

export default async function SharedSettlementPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const serviceClient = createServiceClient();
  const resolvedParams = await params;
  const token = resolvedParams?.token ?? "";

  // Look up share link using service role
  const { data: shareLink, error: shareLinkError } = await serviceClient
    .from("share_links")
    .select("show_id, is_active")
    .eq("token", token)
    .single();

  // If link doesn't exist or is inactive, show 404
  if (shareLinkError || !shareLink || !shareLink.is_active) {
    notFound();
  }

  // Fetch show data using service role
  const { data: show, error: showError } = await serviceClient
    .from("shows")
    .select("*")
    .eq("id", shareLink.show_id)
    .single();

  if (showError || !show) {
    notFound();
  }

  const typedShow = show as Show;
  let authorEmail: string | null = null;
  try {
    const { data: userData } = await serviceClient.auth.admin.getUserById(
      typedShow.user_id
    );
    authorEmail = userData?.user?.email ?? null;
  } catch {
    authorEmail = null;
  }

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: toAbsoluteUrl("/"),
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Shared Settlement",
        item: toAbsoluteUrl("/s"),
      },
    ],
  };

  return (
    <MarketingShell>
      <main className="settlement-packet-container">
        <JsonLd data={breadcrumbSchema} />
        <div className="settlement-packet-header">
          <PageHeader
            title="Show Settlement Calculator"
            description="Settlement Report"
            action={<SharePagePrintButton />}
          />
          {authorEmail && (
            <p className="settlement-report-author">Report by {authorEmail}</p>
          )}
        </div>

        <Card className="settlement-packet-content" variant="default" padding="lg">
        {/* Show Info Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Information</h2>
          <DescriptionList>
            {typedShow.title && (
              <DescriptionList.Item label="Show Name:" value={typedShow.title} />
            )}
            {typedShow.inputs.artistName && (
              <DescriptionList.Item label="Artist:" value={typedShow.inputs.artistName} />
            )}
            {typedShow.show_date && (
              <DescriptionList.Item
                label="Show Date:"
                value={new Date(typedShow.show_date).toLocaleDateString()}
              />
            )}
          </DescriptionList>
        </section>

        {/* Deal Structure Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Deal Structure</h2>
          <DescriptionList>
            <DescriptionList.Item
              label="Deal Type:"
              value={formatDealType(typedShow.inputs.dealType || "")}
            />
            {typedShow.inputs.guarantee && (
              <DescriptionList.Item
                label="Guarantee Amount:"
                value={formatCurrency(parseFloat(typedShow.inputs.guarantee))}
              />
            )}
            {typedShow.inputs.percentage && (
              <DescriptionList.Item
                label="Percentage:"
                value={`${typedShow.inputs.percentage}%`}
              />
            )}
          </DescriptionList>
        </section>

        {/* Show Details Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Details</h2>
          <DescriptionList>
            {typedShow.inputs.ticketTiers && typedShow.inputs.ticketTiers.length > 1 ? (
              typedShow.inputs.ticketTiers.map((tier, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${tier.name || "Tier"}:`}
                  value={`${formatCurrency(parseFloat(tier.price))} × ${tier.sold} sold${parseInt(tier.comps || "0") > 0 ? `, ${tier.comps} comps` : ''}`}
                />
              ))
            ) : (
              <>
                {(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice) && (
                  <DescriptionList.Item
                    label="Ticket Price:"
                    value={formatCurrency(parseFloat(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice || "0"))}
                  />
                )}
                {(typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold) && (
                  <DescriptionList.Item
                    label="Tickets Sold:"
                    value={typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold}
                  />
                )}
                {parseInt(typedShow.inputs.ticketTiers?.[0]?.comps || "0") > 0 && (
                  <DescriptionList.Item
                    label="Comps:"
                    value={typedShow.inputs.ticketTiers![0].comps}
                  />
                )}
              </>
            )}
            {typedShow.inputs.capacity && (
              <DescriptionList.Item
                label="Venue Capacity:"
                value={typedShow.inputs.capacity}
              />
            )}
            {typedShow.inputs.taxRate && (
              <DescriptionList.Item
                label="Tax Rate:"
                value={`${typedShow.inputs.taxRate}%`}
              />
            )}
            {typedShow.inputs.expenseItems && typedShow.inputs.expenseItems.length > 0 ? (
              typedShow.inputs.expenseItems.map((item, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${item.label || "Expense"}:`}
                  value={formatCurrency(parseFloat(item.amount))}
                />
              ))
            ) : typedShow.inputs.totalExpenses ? (
              <DescriptionList.Item
                label="Total Expenses:"
                value={formatCurrency(parseFloat(typedShow.inputs.totalExpenses))}
              />
            ) : null}
          </DescriptionList>
        </section>

        {/* Settlement Breakdown */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Settlement Breakdown</h2>
          <BreakdownList>
            {typedShow.results.ticketTiers && typedShow.results.ticketTiers.length > 1 ? (
              <>
                {typedShow.results.ticketTiers.map((tier, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={`${tier.name} (${tier.sold} × ${formatCurrency(tier.price)})`}
                    value={formatCurrency(tier.revenue)}
                  />
                ))}
                <BreakdownList.Row
                  label={`Gross Revenue (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})`}
                  value={formatCurrency(typedShow.results.grossRevenue)}
                />
              </>
            ) : (
              <BreakdownList.Row
                label={`Gross Revenue${typedShow.results.totalTicketsSold ? ` (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})` : ''}`}
                value={formatCurrency(typedShow.results.grossRevenue)}
              />
            )}
            <BreakdownList.Row
              label="Tax"
              value={`−${formatCurrency(typedShow.results.taxAmount)}`}
              variant="negative"
            />
            {typedShow.results.expenseItems && typedShow.results.expenseItems.length > 0 ? (
              <>
                {typedShow.results.expenseItems.map((item, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={item.label}
                    value={`−${formatCurrency(item.amount)}`}
                    variant="negative"
                  />
                ))}
                {typedShow.results.expenseItems.length > 1 && (
                  <BreakdownList.Row
                    label="Total Expenses"
                    value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                    variant="negative"
                  />
                )}
              </>
            ) : (
              <BreakdownList.Row
                label="Expenses"
                value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                variant="negative"
              />
            )}
            <BreakdownList.Row
              label="Net Profit"
              value={formatCurrency(typedShow.results.netProfit)}
              variant="highlight"
            />
            <BreakdownList.Divider />
            <BreakdownList.Row
              label="Artist Payout"
              value={formatCurrency(typedShow.results.artistPayout)}
              variant="success"
            />
            <BreakdownList.Row
              label="Promoter/House Settlement"
              value={formatCurrency(typedShow.results.venuePayout)}
              variant="warning"
            />
          </BreakdownList>
        </section>

        {/* Footer */}
        <footer className="ds-card-footer">
          <p className="ds-card-footer-text">
            Generated on {new Date().toLocaleDateString()} via{" "}
            <Link href="/" className="ds-card-footer-link">
              Show Settlement Calculator
            </Link>
          </p>
          <p className="ds-card-footer-note">
            This is a shared settlement report. Sign up to create your own settlements.
          </p>
        </footer>
      </Card>
      </main>
    </MarketingShell>
  );
}
