import type { Metadata } from "next";
import { createServiceClient } from "@/lib/supabase/service";
import { notFound } from "next/navigation";
import Link from "next/link";
import JsonLd from "@/app/components/JsonLd";
import { buildPageMetadata, toAbsoluteUrl } from "@/lib/seo";
import { MarketingShell } from "@/components/ui/MarketingShell";
import { Card } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { DescriptionList } from "@/components/ui/DescriptionList";
import { BreakdownList } from "@/components/ui/BreakdownList";
import { SharePagePrintButton } from "./SharePagePrintButton";
import { AcknowledgeForm } from "./AcknowledgeForm";
import "./shared-settlement.css";

/**
 * Public share page for settlements
 * Typography matches rest of app: --text-2xl (page title), --text-sm (section titles), --text-base (values), --text-lg (highlight row).
 * Server component that fetches show data using service role to bypass RLS
 * No authentication required - access granted via valid active token
 */

interface ArtistInput {
  artistName?: string;
  dealType?: string;
  guarantee?: string;
  percentage?: string;
  breakeven?: string;
  deposit?: string;
  withholdingRate?: string;
  withholdingState?: string;
  buyoutItems?: { label: string; amount: string }[];
  buyoutMode?: string;
}

interface ArtistResultEntry {
  artistName: string;
  dealType: string;
  artistPayout: number;
  overage?: number;
  breakeven?: number;
  withholdingAmount?: number;
  withholdingState?: string;
  buyoutItems?: { label: string; amount: number }[];
  totalBuyouts?: number;
  deposit: number;
  balanceDue: number;
}

interface Show {
  id: string;
  user_id: string;
  title: string | null;
  show_date: string | null;
  inputs: {
    artists?: ArtistInput[];
    artistName?: string;
    ticketTiers?: { name: string; price: string; sold: string; comps?: string }[];
    capacity?: string;
    ticketPrice?: string;
    ticketsSold?: string;
    taxRate?: string;
    taxMode?: string;
    ccFeeRate?: string;
    ccFeeMode?: string;
    totalExpenses?: string;
    expenseItems?: { label: string; amount: string; note?: string }[];
    notes?: string;
    dealType?: string;
    guarantee?: string;
    percentage?: string;
    breakeven?: string;
    deposit?: string;
    withholdingRate?: string;
    withholdingState?: string;
    buyoutItems?: { label: string; amount: string }[];
    buyoutMode?: string;
    merchGross?: string;
    merchVenuePercent?: string;
  };
  results: {
    grossRevenue: number;
    ticketTiers?: { name: string; price: number; sold: number; comps: number; revenue: number }[];
    totalTicketsSold?: number;
    totalComps?: number;
    taxAmount: number;
    totalExpenses: number;
    expenseItems?: { label: string; amount: number; note?: string }[];
    notes?: string;
    netProfit: number;
    artists?: ArtistResultEntry[];
    artistPayout: number;
    overage?: number;
    breakeven?: number;
    deposit?: number;
    balanceDue?: number;
    ccFees?: number;
    withholdingAmount?: number;
    withholdingState?: string;
    buyoutItems?: { label: string; amount: number }[];
    totalBuyouts?: number;
    venuePayout: number;
    merchGross?: number;
    merchVenueCut?: number;
    merchNetToArtist?: number;
    totalDueToArtist?: number;
    calculatedAt?: string;
    acknowledgments?: { name: string; email: string; timestamp: string }[];
  };
  created_at: string;
  updated_at: string;
}

export async function generateMetadata(): Promise<Metadata> {
  return buildPageMetadata({
    title: "Shared Settlement - GigSettle",
    description: "View a shared settlement packet generated by GigSettle.",
    path: "/s",
    noIndex: true,
  });
}

/**
 * Formats a number as USD currency
 */
function formatCurrency(amount: number): string {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return formatter.format(amount);
}

/**
 * Formats deal type for display
 */
function formatDealType(dealType: string): string {
  switch (dealType) {
    case "guarantee":
      return "Guarantee";
    case "percentage":
      return "Percentage of Net";
    case "guarantee_vs_percentage":
      return "Guarantee vs Percentage (whichever is higher)";
    case "guarantee_plus_percentage":
      return "Guarantee + Back-End Percentage";
    case "percentage_of_gross":
      return "Percentage of Gross (before deductions)";
    case "door_deal":
      return "Door Deal (% of gross after tax)";
    default:
      return dealType;
  }
}

export default async function SharedSettlementPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const serviceClient = createServiceClient();
  const resolvedParams = await params;
  const token = resolvedParams?.token ?? "";

  // Look up share link using service role
  const { data: shareLink, error: shareLinkError } = await serviceClient
    .from("share_links")
    .select("show_id, is_active")
    .eq("token", token)
    .single();

  // If link doesn't exist or is inactive, show 404
  if (shareLinkError || !shareLink || !shareLink.is_active) {
    notFound();
  }

  // Fetch show data using service role
  const { data: show, error: showError } = await serviceClient
    .from("shows")
    .select("*")
    .eq("id", shareLink.show_id)
    .single();

  if (showError || !show) {
    notFound();
  }

  const typedShow = show as Show;
  let authorEmail: string | null = null;
  try {
    const { data: userData } = await serviceClient.auth.admin.getUserById(
      typedShow.user_id
    );
    authorEmail = userData?.user?.email ?? null;
  } catch {
    authorEmail = null;
  }

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: toAbsoluteUrl("/"),
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Shared Settlement",
        item: toAbsoluteUrl("/s"),
      },
    ],
  };

  return (
    <MarketingShell>
      <main className="settlement-packet-container">
        <JsonLd data={breadcrumbSchema} />
        <div className="settlement-packet-header">
          <PageHeader
            title="Show Settlement Calculator"
            description="Settlement Report"
            action={<SharePagePrintButton />}
          />
          {authorEmail && (
            <p className="settlement-report-author">Report by {authorEmail}</p>
          )}
        </div>

        <Card className="settlement-packet-content" variant="default" padding="lg">
        {/* Show Info Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Information</h2>
          <DescriptionList>
            {typedShow.title && (
              <DescriptionList.Item label="Show Name:" value={typedShow.title} />
            )}
            {(() => {
              const artistNames = typedShow.results.artists
                ? typedShow.results.artists.map((a) => a.artistName).filter(Boolean).join(", ")
                : typedShow.inputs.artistName || "";
              return artistNames ? (
                <DescriptionList.Item label={typedShow.results.artists && typedShow.results.artists.length > 1 ? "Artists:" : "Artist:"} value={artistNames} />
              ) : null;
            })()}
            {typedShow.show_date && (
              <DescriptionList.Item
                label="Show Date:"
                value={new Date(typedShow.show_date).toLocaleDateString()}
              />
            )}
          </DescriptionList>
        </section>

        {/* Notes */}
        {(typedShow.results.notes || typedShow.inputs.notes) && (
          <section className="settlement-section">
            <h2 className="ds-section-title">Notes</h2>
            <p className="settlement-notes-text">{typedShow.results.notes || typedShow.inputs.notes}</p>
          </section>
        )}

        {/* Deal Structure Section */}
        {(() => {
          const artistInputs: ArtistInput[] = typedShow.inputs.artists && typedShow.inputs.artists.length > 0
            ? typedShow.inputs.artists
            : [{
                artistName: typedShow.inputs.artistName,
                dealType: typedShow.inputs.dealType,
                guarantee: typedShow.inputs.guarantee,
                percentage: typedShow.inputs.percentage,
                breakeven: typedShow.inputs.breakeven,
                deposit: typedShow.inputs.deposit,
                withholdingRate: typedShow.inputs.withholdingRate,
                withholdingState: typedShow.inputs.withholdingState,
                buyoutItems: typedShow.inputs.buyoutItems,
                buyoutMode: typedShow.inputs.buyoutMode,
              }];
          const isMulti = artistInputs.length > 1;

          return artistInputs.map((ai, idx) => (
            <section key={idx} className="settlement-section">
              <h2 className="ds-section-title">
                {isMulti ? `${ai.artistName || `Artist ${idx + 1}`} — Deal Structure` : "Deal Structure"}
              </h2>
              <DescriptionList>
                <DescriptionList.Item
                  label="Deal Type:"
                  value={formatDealType(ai.dealType || "")}
                />
                {ai.guarantee && (
                  <DescriptionList.Item
                    label="Guarantee Amount:"
                    value={formatCurrency(parseFloat(ai.guarantee))}
                  />
                )}
                {ai.percentage && (
                  <DescriptionList.Item
                    label={ai.dealType === "guarantee_plus_percentage" ? "Back-End Percentage:" : "Percentage:"}
                    value={`${ai.percentage}%`}
                  />
                )}
                {ai.breakeven && parseFloat(ai.breakeven) > 0 && (
                  <DescriptionList.Item
                    label="Breakeven Point:"
                    value={formatCurrency(parseFloat(ai.breakeven))}
                  />
                )}
                {ai.deposit && parseFloat(ai.deposit) > 0 && (
                  <DescriptionList.Item
                    label="Deposit / Advance Paid:"
                    value={formatCurrency(parseFloat(ai.deposit))}
                  />
                )}
                {ai.withholdingRate && parseFloat(ai.withholdingRate) > 0 && (
                  <DescriptionList.Item
                    label="Withholding Tax:"
                    value={`${ai.withholdingRate}%${ai.withholdingState ? ` (${ai.withholdingState})` : ''}`}
                  />
                )}
                {ai.buyoutItems && ai.buyoutItems.length > 0 &&
                  ai.buyoutItems.some(b => parseFloat(b.amount) > 0) && (
                  <DescriptionList.Item
                    label="Buyout Handling:"
                    value={ai.buyoutMode === 'show_expense' ? 'Show expense' : 'Deducted from balance'}
                  />
                )}
              </DescriptionList>
            </section>
          ));
        })()}

        {/* Show Details Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Details</h2>
          <DescriptionList>
            {typedShow.inputs.ticketTiers && typedShow.inputs.ticketTiers.length > 1 ? (
              typedShow.inputs.ticketTiers.map((tier, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${tier.name || "Tier"}:`}
                  value={`${formatCurrency(parseFloat(tier.price))} × ${tier.sold} sold${parseInt(tier.comps || "0") > 0 ? `, ${tier.comps} comps` : ''}`}
                />
              ))
            ) : (
              <>
                {(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice) && (
                  <DescriptionList.Item
                    label="Ticket Price:"
                    value={formatCurrency(parseFloat(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice || "0"))}
                  />
                )}
                {(typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold) && (
                  <DescriptionList.Item
                    label="Tickets Sold:"
                    value={typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold}
                  />
                )}
                {parseInt(typedShow.inputs.ticketTiers?.[0]?.comps || "0") > 0 && (
                  <DescriptionList.Item
                    label="Comps:"
                    value={typedShow.inputs.ticketTiers![0].comps}
                  />
                )}
              </>
            )}
            {typedShow.inputs.capacity && (
              <DescriptionList.Item
                label="Venue Capacity:"
                value={typedShow.inputs.capacity}
              />
            )}
            {typedShow.inputs.taxRate && (
              <DescriptionList.Item
                label="Tax Rate:"
                value={`${typedShow.inputs.taxRate}%${typedShow.inputs.taxMode === 'inclusive' ? ' (included in price)' : ''}`}
              />
            )}
            {typedShow.inputs.ccFeeRate && parseFloat(typedShow.inputs.ccFeeRate) > 0 && (
              <DescriptionList.Item
                label="CC Processing Fee:"
                value={`${typedShow.inputs.ccFeeRate}%${typedShow.inputs.ccFeeMode === 'off_top' ? ' (off the top)' : ' (venue expense)'}`}
              />
            )}
            {typedShow.inputs.expenseItems && typedShow.inputs.expenseItems.length > 0 ? (
              typedShow.inputs.expenseItems.map((item, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${item.label || "Expense"}${item.note ? ` (${item.note})` : ""}:`}
                  value={formatCurrency(parseFloat(item.amount))}
                />
              ))
            ) : typedShow.inputs.totalExpenses ? (
              <DescriptionList.Item
                label="Total Expenses:"
                value={formatCurrency(parseFloat(typedShow.inputs.totalExpenses))}
              />
            ) : null}
          </DescriptionList>
        </section>

        {/* Settlement Breakdown */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Settlement Breakdown</h2>
          <BreakdownList>
            {typedShow.results.ticketTiers && typedShow.results.ticketTiers.length > 1 ? (
              <>
                {typedShow.results.ticketTiers.map((tier, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={`${tier.name} (${tier.sold} × ${formatCurrency(tier.price)})`}
                    value={formatCurrency(tier.revenue)}
                  />
                ))}
                <BreakdownList.Row
                  label={`Gross Revenue (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})`}
                  value={formatCurrency(typedShow.results.grossRevenue)}
                />
              </>
            ) : (
              <BreakdownList.Row
                label={`Gross Revenue${typedShow.results.totalTicketsSold ? ` (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})` : ''}`}
                value={formatCurrency(typedShow.results.grossRevenue)}
              />
            )}
            <BreakdownList.Row
              label={`Tax (${typedShow.inputs.taxRate || '0'}%${typedShow.inputs.taxMode === 'inclusive' ? ', included in price' : ''})`}
              value={`−${formatCurrency(typedShow.results.taxAmount)}`}
              variant="negative"
            />
            {typedShow.results.ccFees != null && typedShow.results.ccFees > 0 && typedShow.inputs.ccFeeMode === 'off_top' && (
              <BreakdownList.Row
                label={`CC Processing Fees (${typedShow.inputs.ccFeeRate}%)`}
                value={`−${formatCurrency(typedShow.results.ccFees)}`}
                variant="negative"
              />
            )}
            {typedShow.results.expenseItems && typedShow.results.expenseItems.length > 0 ? (
              <>
                {typedShow.results.expenseItems.map((item, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={item.note ? `${item.label} — ${item.note}` : item.label}
                    value={`−${formatCurrency(item.amount)}`}
                    variant="negative"
                  />
                ))}
                {(() => {
                  if (typedShow.results.artists && typedShow.results.artists.length > 0) {
                    const inputArtists = typedShow.inputs.artists || [typedShow.inputs];
                    return typedShow.results.artists.flatMap((ar, arIdx) => {
                      const ai = inputArtists[arIdx] || {};
                      if (ai.buyoutMode !== "show_expense" || !ar.buyoutItems) return [];
                      return ar.buyoutItems.map((item, bi) => (
                        <BreakdownList.Row
                          key={`buyout-exp-${arIdx}-${bi}`}
                          label={`${item.label} (buyout${typedShow.results.artists!.length > 1 ? ` — ${ar.artistName}` : ''})`}
                          value={`−${formatCurrency(item.amount)}`}
                          variant="negative"
                        />
                      ));
                    });
                  }
                  if (typedShow.results.buyoutItems && typedShow.results.buyoutItems.length > 0 && typedShow.inputs.buyoutMode === 'show_expense') {
                    return typedShow.results.buyoutItems.map((item, index) => (
                      <BreakdownList.Row
                        key={`buyout-exp-${index}`}
                        label={`${item.label} (buyout)`}
                        value={`−${formatCurrency(item.amount)}`}
                        variant="negative"
                      />
                    ));
                  }
                  return null;
                })()}
                {typedShow.results.expenseItems.length > 1 && (
                  <BreakdownList.Row
                    label="Total Expenses"
                    value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                    variant="negative"
                  />
                )}
              </>
            ) : (
              <BreakdownList.Row
                label="Expenses"
                value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                variant="negative"
              />
            )}
            <BreakdownList.Row
              label="Net Profit"
              value={formatCurrency(typedShow.results.netProfit)}
              variant="highlight"
            />
            <BreakdownList.Divider />
            {(() => {
              const artistResults = typedShow.results.artists && typedShow.results.artists.length > 0
                ? typedShow.results.artists
                : [{
                    artistName: typedShow.inputs.artistName || "Artist",
                    dealType: typedShow.inputs.dealType || "guarantee",
                    artistPayout: typedShow.results.artistPayout,
                    overage: typedShow.results.overage,
                    breakeven: typedShow.results.breakeven,
                    withholdingAmount: typedShow.results.withholdingAmount,
                    withholdingState: typedShow.results.withholdingState,
                    buyoutItems: typedShow.results.buyoutItems,
                    totalBuyouts: typedShow.results.totalBuyouts,
                    deposit: typedShow.results.deposit ?? 0,
                    balanceDue: typedShow.results.balanceDue ?? 0,
                  }];
              const artistInputs: ArtistInput[] = typedShow.inputs.artists && typedShow.inputs.artists.length > 0
                ? typedShow.inputs.artists
                : [typedShow.inputs];
              const isMulti = artistResults.length > 1;

              return artistResults.map((ar, arIdx) => {
                const ai = artistInputs[arIdx] || {};
                const hasDeductions = ar.deposit > 0 || (ar.withholdingAmount != null && ar.withholdingAmount > 0) || (ar.totalBuyouts != null && ar.totalBuyouts > 0 && ai.buyoutMode !== 'show_expense');
                return (
                  <div key={arIdx}>
                    {isMulti && arIdx > 0 && <BreakdownList.Divider />}
                    {isMulti && (
                      <BreakdownList.Row label={ar.artistName} value="" variant="highlight" />
                    )}
                    {ar.overage != null && ar.breakeven != null && (
                      <>
                        <BreakdownList.Row
                          label="Guarantee"
                          value={formatCurrency(ar.artistPayout - ar.overage)}
                        />
                        <BreakdownList.Row
                          label="Breakeven Point"
                          value={formatCurrency(ar.breakeven)}
                        />
                        <BreakdownList.Row
                          label="Back-End Overage"
                          value={formatCurrency(ar.overage)}
                        />
                      </>
                    )}
                    <BreakdownList.Row
                      label={
                        ar.overage != null
                          ? `${isMulti ? ar.artistName + ' ' : ''}Payout (Guarantee + Overage)`
                          : ar.dealType === "percentage_of_gross"
                          ? `${isMulti ? ar.artistName + ' ' : 'Artist '}Payout (${ai.percentage}% of Gross)`
                          : ar.dealType === "door_deal"
                          ? `${isMulti ? ar.artistName + ' ' : 'Artist '}Payout (${ai.percentage}% of Gross After Tax)`
                          : `${isMulti ? ar.artistName + ' ' : 'Artist '}Payout`
                      }
                      value={formatCurrency(ar.artistPayout)}
                      variant="success"
                    />
                    {ar.withholdingAmount != null && ar.withholdingAmount > 0 && (
                      <BreakdownList.Row
                        label={`Withholding Tax (${ai.withholdingRate}%${ar.withholdingState ? `, ${ar.withholdingState}` : ''})`}
                        value={`−${formatCurrency(ar.withholdingAmount)}`}
                        variant="negative"
                      />
                    )}
                    {ar.buyoutItems && ar.buyoutItems.length > 0 && ai.buyoutMode !== 'show_expense' && (
                      ar.buyoutItems.map((item, index) => (
                        <BreakdownList.Row
                          key={`buyout-${arIdx}-${index}`}
                          label={item.label}
                          value={`−${formatCurrency(item.amount)}`}
                          variant="negative"
                        />
                      ))
                    )}
                    {hasDeductions && (
                      <>
                        {ar.deposit > 0 && (
                          <BreakdownList.Row
                            label="Deposit Paid"
                            value={`−${formatCurrency(ar.deposit)}`}
                            variant="negative"
                          />
                        )}
                        <BreakdownList.Row
                          label={ar.balanceDue < 0
                            ? "Overpayment (due back to promoter)"
                            : "Balance Due at Settlement"}
                          value={formatCurrency(Math.abs(ar.balanceDue))}
                          variant={ar.balanceDue < 0 ? "warning" : "success"}
                        />
                      </>
                    )}
                  </div>
                );
              });
            })()}
            {typedShow.results.artists && typedShow.results.artists.length > 1 && (
              <>
                <BreakdownList.Divider />
                <BreakdownList.Row
                  label="Total Artist Payouts"
                  value={formatCurrency(typedShow.results.artistPayout)}
                  variant="highlight"
                />
              </>
            )}
            {typedShow.results.ccFees != null && typedShow.results.ccFees > 0 && typedShow.inputs.ccFeeMode !== 'off_top' && (
              <BreakdownList.Row
                label={`CC Processing Fees (${typedShow.inputs.ccFeeRate}%, venue cost)`}
                value={`−${formatCurrency(typedShow.results.ccFees)}`}
                variant="negative"
              />
            )}
            <BreakdownList.Row
              label={typedShow.results.venuePayout < 0 ? "Venue Loss" : "Promoter/House Settlement"}
              value={`${typedShow.results.venuePayout < 0 ? '−' : ''}${formatCurrency(Math.abs(typedShow.results.venuePayout))}`}
              variant={typedShow.results.venuePayout < 0 ? "warning" : "warning"}
            />
          </BreakdownList>
        </section>

        {typedShow.results.merchGross != null && typedShow.results.merchGross > 0 && (
          <section className="settlement-section">
            <h2 className="ds-section-title">Merch Settlement</h2>
            <BreakdownList>
              <BreakdownList.Row
                label="Gross Merch Sales"
                value={formatCurrency(typedShow.results.merchGross)}
              />
              <BreakdownList.Row
                label={`Venue Merch Cut (${typedShow.inputs.merchVenuePercent || '0'}%)`}
                value={`−${formatCurrency(typedShow.results.merchVenueCut ?? 0)}`}
                variant="negative"
              />
              <BreakdownList.Row
                label="Net Merch to Artist"
                value={formatCurrency(typedShow.results.merchNetToArtist ?? 0)}
                variant="success"
              />
            </BreakdownList>
          </section>
        )}

        {typedShow.results.totalDueToArtist != null && (
          <section className="settlement-section">
            <h2 className="ds-section-title">Total</h2>
            <BreakdownList>
              <BreakdownList.Row
                label="Show Balance Due"
                value={formatCurrency(
                  typedShow.results.deposit != null && typedShow.results.deposit > 0
                    ? (typedShow.results.balanceDue ?? typedShow.results.artistPayout)
                    : typedShow.results.artistPayout
                )}
              />
              <BreakdownList.Row
                label="Net Merch to Artist"
                value={formatCurrency(typedShow.results.merchNetToArtist ?? 0)}
              />
              <BreakdownList.Row
                label="Total Due to Artist"
                value={formatCurrency(typedShow.results.totalDueToArtist)}
                variant="success"
              />
            </BreakdownList>
          </section>
        )}

        {/* Acknowledgment */}
        <AcknowledgeForm
          token={token}
          initialAcknowledgments={typedShow.results.acknowledgments || []}
        />

        {/* Footer */}
        <footer className="ds-card-footer">
          <p className="ds-card-footer-text">
            {typedShow.results.calculatedAt && (
              <>Calculated {new Date(typedShow.results.calculatedAt).toLocaleString()} · </>
            )}
            Generated via{" "}
            <Link href="/" className="ds-card-footer-link">
              Show Settlement Calculator
            </Link>
          </p>
          <p className="ds-card-footer-note">
            This is a shared settlement report. Sign up to create your own settlements.
          </p>
        </footer>
      </Card>
      </main>
    </MarketingShell>
  );
}
