import type { Metadata } from "next";
import { createServiceClient } from "@/lib/supabase/service";
import { notFound } from "next/navigation";
import Link from "next/link";
import JsonLd from "@/app/components/JsonLd";
import { buildPageMetadata, toAbsoluteUrl } from "@/lib/seo";
import { MarketingShell } from "@/components/ui/MarketingShell";
import { Card } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { DescriptionList } from "@/components/ui/DescriptionList";
import { BreakdownList } from "@/components/ui/BreakdownList";
import { SharePagePrintButton } from "./SharePagePrintButton";
import "./shared-settlement.css";

/**
 * Public share page for settlements
 * Typography matches rest of app: --text-2xl (page title), --text-sm (section titles), --text-base (values), --text-lg (highlight row).
 * Server component that fetches show data using service role to bypass RLS
 * No authentication required - access granted via valid active token
 */

interface Show {
  id: string;
  user_id: string;
  title: string | null;
  show_date: string | null;
  inputs: {
    artistName?: string;
    ticketTiers?: { name: string; price: string; sold: string; comps?: string }[];
    capacity?: string;
    ticketPrice?: string;
    ticketsSold?: string;
    taxRate?: string;
    taxMode?: string;
    ccFeeRate?: string;
    ccFeeMode?: string;
    totalExpenses?: string;
    expenseItems?: { label: string; amount: string }[];
    dealType?: string;
    guarantee?: string;
    percentage?: string;
    breakeven?: string;
    deposit?: string;
    withholdingRate?: string;
    withholdingState?: string;
    buyoutItems?: { label: string; amount: string }[];
    buyoutMode?: string;
    merchGross?: string;
    merchVenuePercent?: string;
  };
  results: {
    grossRevenue: number;
    ticketTiers?: { name: string; price: number; sold: number; comps: number; revenue: number }[];
    totalTicketsSold?: number;
    totalComps?: number;
    taxAmount: number;
    totalExpenses: number;
    expenseItems?: { label: string; amount: number }[];
    netProfit: number;
    artistPayout: number;
    overage?: number;
    breakeven?: number;
    deposit?: number;
    balanceDue?: number;
    ccFees?: number;
    withholdingAmount?: number;
    withholdingState?: string;
    buyoutItems?: { label: string; amount: number }[];
    totalBuyouts?: number;
    venuePayout: number;
    merchGross?: number;
    merchVenueCut?: number;
    merchNetToArtist?: number;
    totalDueToArtist?: number;
    calculatedAt?: string;
  };
  created_at: string;
  updated_at: string;
}

export async function generateMetadata(): Promise<Metadata> {
  return buildPageMetadata({
    title: "Shared Settlement - GigSettle",
    description: "View a shared settlement packet generated by GigSettle.",
    path: "/s",
    noIndex: true,
  });
}

/**
 * Formats a number as USD currency
 */
function formatCurrency(amount: number): string {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return formatter.format(amount);
}

/**
 * Formats deal type for display
 */
function formatDealType(dealType: string): string {
  switch (dealType) {
    case "guarantee":
      return "Guarantee";
    case "percentage":
      return "Percentage of Net";
    case "guarantee_vs_percentage":
      return "Guarantee vs Percentage (whichever is higher)";
    case "guarantee_plus_percentage":
      return "Guarantee + Back-End Percentage";
    case "percentage_of_gross":
      return "Percentage of Gross (before deductions)";
    case "door_deal":
      return "Door Deal (% of gross after tax)";
    default:
      return dealType;
  }
}

export default async function SharedSettlementPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const serviceClient = createServiceClient();
  const resolvedParams = await params;
  const token = resolvedParams?.token ?? "";

  // Look up share link using service role
  const { data: shareLink, error: shareLinkError } = await serviceClient
    .from("share_links")
    .select("show_id, is_active")
    .eq("token", token)
    .single();

  // If link doesn't exist or is inactive, show 404
  if (shareLinkError || !shareLink || !shareLink.is_active) {
    notFound();
  }

  // Fetch show data using service role
  const { data: show, error: showError } = await serviceClient
    .from("shows")
    .select("*")
    .eq("id", shareLink.show_id)
    .single();

  if (showError || !show) {
    notFound();
  }

  const typedShow = show as Show;
  let authorEmail: string | null = null;
  try {
    const { data: userData } = await serviceClient.auth.admin.getUserById(
      typedShow.user_id
    );
    authorEmail = userData?.user?.email ?? null;
  } catch {
    authorEmail = null;
  }

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: toAbsoluteUrl("/"),
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Shared Settlement",
        item: toAbsoluteUrl("/s"),
      },
    ],
  };

  return (
    <MarketingShell>
      <main className="settlement-packet-container">
        <JsonLd data={breadcrumbSchema} />
        <div className="settlement-packet-header">
          <PageHeader
            title="Show Settlement Calculator"
            description="Settlement Report"
            action={<SharePagePrintButton />}
          />
          {authorEmail && (
            <p className="settlement-report-author">Report by {authorEmail}</p>
          )}
        </div>

        <Card className="settlement-packet-content" variant="default" padding="lg">
        {/* Show Info Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Information</h2>
          <DescriptionList>
            {typedShow.title && (
              <DescriptionList.Item label="Show Name:" value={typedShow.title} />
            )}
            {typedShow.inputs.artistName && (
              <DescriptionList.Item label="Artist:" value={typedShow.inputs.artistName} />
            )}
            {typedShow.show_date && (
              <DescriptionList.Item
                label="Show Date:"
                value={new Date(typedShow.show_date).toLocaleDateString()}
              />
            )}
          </DescriptionList>
        </section>

        {/* Deal Structure Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Deal Structure</h2>
          <DescriptionList>
            <DescriptionList.Item
              label="Deal Type:"
              value={formatDealType(typedShow.inputs.dealType || "")}
            />
            {typedShow.inputs.guarantee && (
              <DescriptionList.Item
                label="Guarantee Amount:"
                value={formatCurrency(parseFloat(typedShow.inputs.guarantee))}
              />
            )}
            {typedShow.inputs.percentage && (
              <DescriptionList.Item
                label={typedShow.inputs.dealType === "guarantee_plus_percentage" ? "Back-End Percentage:" : "Percentage:"}
                value={`${typedShow.inputs.percentage}%`}
              />
            )}
            {typedShow.inputs.breakeven && parseFloat(typedShow.inputs.breakeven) > 0 && (
              <DescriptionList.Item
                label="Breakeven Point:"
                value={formatCurrency(parseFloat(typedShow.inputs.breakeven))}
              />
            )}
            {typedShow.inputs.deposit && parseFloat(typedShow.inputs.deposit) > 0 && (
              <DescriptionList.Item
                label="Deposit / Advance Paid:"
                value={formatCurrency(parseFloat(typedShow.inputs.deposit))}
              />
            )}
            {typedShow.inputs.withholdingRate && parseFloat(typedShow.inputs.withholdingRate) > 0 && (
              <DescriptionList.Item
                label="Withholding Tax:"
                value={`${typedShow.inputs.withholdingRate}%${typedShow.inputs.withholdingState ? ` (${typedShow.inputs.withholdingState})` : ''}`}
              />
            )}
            {typedShow.inputs.buyoutItems && typedShow.inputs.buyoutItems.length > 0 &&
              typedShow.inputs.buyoutItems.some(b => parseFloat(b.amount) > 0) && (
              <DescriptionList.Item
                label="Buyout Handling:"
                value={typedShow.inputs.buyoutMode === 'show_expense' ? 'Show expense' : 'Deducted from balance'}
              />
            )}
          </DescriptionList>
        </section>

        {/* Show Details Section */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Show Details</h2>
          <DescriptionList>
            {typedShow.inputs.ticketTiers && typedShow.inputs.ticketTiers.length > 1 ? (
              typedShow.inputs.ticketTiers.map((tier, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${tier.name || "Tier"}:`}
                  value={`${formatCurrency(parseFloat(tier.price))} × ${tier.sold} sold${parseInt(tier.comps || "0") > 0 ? `, ${tier.comps} comps` : ''}`}
                />
              ))
            ) : (
              <>
                {(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice) && (
                  <DescriptionList.Item
                    label="Ticket Price:"
                    value={formatCurrency(parseFloat(typedShow.inputs.ticketTiers?.[0]?.price || typedShow.inputs.ticketPrice || "0"))}
                  />
                )}
                {(typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold) && (
                  <DescriptionList.Item
                    label="Tickets Sold:"
                    value={typedShow.inputs.ticketTiers?.[0]?.sold || typedShow.inputs.ticketsSold}
                  />
                )}
                {parseInt(typedShow.inputs.ticketTiers?.[0]?.comps || "0") > 0 && (
                  <DescriptionList.Item
                    label="Comps:"
                    value={typedShow.inputs.ticketTiers![0].comps}
                  />
                )}
              </>
            )}
            {typedShow.inputs.capacity && (
              <DescriptionList.Item
                label="Venue Capacity:"
                value={typedShow.inputs.capacity}
              />
            )}
            {typedShow.inputs.taxRate && (
              <DescriptionList.Item
                label="Tax Rate:"
                value={`${typedShow.inputs.taxRate}%${typedShow.inputs.taxMode === 'inclusive' ? ' (included in price)' : ''}`}
              />
            )}
            {typedShow.inputs.ccFeeRate && parseFloat(typedShow.inputs.ccFeeRate) > 0 && (
              <DescriptionList.Item
                label="CC Processing Fee:"
                value={`${typedShow.inputs.ccFeeRate}%${typedShow.inputs.ccFeeMode === 'off_top' ? ' (off the top)' : ' (venue expense)'}`}
              />
            )}
            {typedShow.inputs.expenseItems && typedShow.inputs.expenseItems.length > 0 ? (
              typedShow.inputs.expenseItems.map((item, index) => (
                <DescriptionList.Item
                  key={index}
                  label={`${item.label || "Expense"}:`}
                  value={formatCurrency(parseFloat(item.amount))}
                />
              ))
            ) : typedShow.inputs.totalExpenses ? (
              <DescriptionList.Item
                label="Total Expenses:"
                value={formatCurrency(parseFloat(typedShow.inputs.totalExpenses))}
              />
            ) : null}
          </DescriptionList>
        </section>

        {/* Settlement Breakdown */}
        <section className="settlement-section">
          <h2 className="ds-section-title">Settlement Breakdown</h2>
          <BreakdownList>
            {typedShow.results.ticketTiers && typedShow.results.ticketTiers.length > 1 ? (
              <>
                {typedShow.results.ticketTiers.map((tier, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={`${tier.name} (${tier.sold} × ${formatCurrency(tier.price)})`}
                    value={formatCurrency(tier.revenue)}
                  />
                ))}
                <BreakdownList.Row
                  label={`Gross Revenue (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})`}
                  value={formatCurrency(typedShow.results.grossRevenue)}
                />
              </>
            ) : (
              <BreakdownList.Row
                label={`Gross Revenue${typedShow.results.totalTicketsSold ? ` (${typedShow.results.totalTicketsSold} sold${typedShow.results.totalComps ? `, ${typedShow.results.totalComps} comps` : ''})` : ''}`}
                value={formatCurrency(typedShow.results.grossRevenue)}
              />
            )}
            <BreakdownList.Row
              label={`Tax (${typedShow.inputs.taxRate || '0'}%${typedShow.inputs.taxMode === 'inclusive' ? ', included in price' : ''})`}
              value={`−${formatCurrency(typedShow.results.taxAmount)}`}
              variant="negative"
            />
            {typedShow.results.ccFees != null && typedShow.results.ccFees > 0 && typedShow.inputs.ccFeeMode === 'off_top' && (
              <BreakdownList.Row
                label={`CC Processing Fees (${typedShow.inputs.ccFeeRate}%)`}
                value={`−${formatCurrency(typedShow.results.ccFees)}`}
                variant="negative"
              />
            )}
            {typedShow.results.expenseItems && typedShow.results.expenseItems.length > 0 ? (
              <>
                {typedShow.results.expenseItems.map((item, index) => (
                  <BreakdownList.Row
                    key={index}
                    label={item.label}
                    value={`−${formatCurrency(item.amount)}`}
                    variant="negative"
                  />
                ))}
                {typedShow.results.buyoutItems && typedShow.results.buyoutItems.length > 0 && typedShow.inputs.buyoutMode === 'show_expense' && (
                  typedShow.results.buyoutItems.map((item, index) => (
                    <BreakdownList.Row
                      key={`buyout-exp-${index}`}
                      label={`${item.label} (buyout)`}
                      value={`−${formatCurrency(item.amount)}`}
                      variant="negative"
                    />
                  ))
                )}
                {(typedShow.results.expenseItems.length > 1 || (typedShow.results.buyoutItems && typedShow.results.buyoutItems.length > 0 && typedShow.inputs.buyoutMode === 'show_expense')) && (
                  <BreakdownList.Row
                    label="Total Expenses"
                    value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                    variant="negative"
                  />
                )}
              </>
            ) : (
              <BreakdownList.Row
                label="Expenses"
                value={`−${formatCurrency(typedShow.results.totalExpenses)}`}
                variant="negative"
              />
            )}
            <BreakdownList.Row
              label="Net Profit"
              value={formatCurrency(typedShow.results.netProfit)}
              variant="highlight"
            />
            <BreakdownList.Divider />
            {typedShow.results.overage != null && typedShow.results.breakeven != null && (
              <>
                <BreakdownList.Row
                  label="Guarantee"
                  value={formatCurrency(typedShow.results.artistPayout - typedShow.results.overage)}
                />
                <BreakdownList.Row
                  label="Breakeven Point"
                  value={formatCurrency(typedShow.results.breakeven)}
                />
                <BreakdownList.Row
                  label="Back-End Overage"
                  value={formatCurrency(typedShow.results.overage)}
                />
              </>
            )}
            <BreakdownList.Row
              label={
                typedShow.results.overage != null
                  ? "Artist Payout (Guarantee + Overage)"
                  : typedShow.inputs.dealType === "percentage_of_gross"
                  ? `Artist Payout (${typedShow.inputs.percentage}% of Gross)`
                  : typedShow.inputs.dealType === "door_deal"
                  ? `Artist Payout (${typedShow.inputs.percentage}% of Gross After Tax)`
                  : "Artist Payout"
              }
              value={formatCurrency(typedShow.results.artistPayout)}
              variant="success"
            />
            {typedShow.results.withholdingAmount != null && typedShow.results.withholdingAmount > 0 && (
              <BreakdownList.Row
                label={`Withholding Tax (${typedShow.inputs.withholdingRate}%${typedShow.results.withholdingState ? `, ${typedShow.results.withholdingState}` : ''})`}
                value={`−${formatCurrency(typedShow.results.withholdingAmount)}`}
                variant="negative"
              />
            )}
            {typedShow.results.buyoutItems && typedShow.results.buyoutItems.length > 0 && typedShow.inputs.buyoutMode !== 'show_expense' && (
              typedShow.results.buyoutItems.map((item, index) => (
                <BreakdownList.Row
                  key={`buyout-${index}`}
                  label={item.label}
                  value={`−${formatCurrency(item.amount)}`}
                  variant="negative"
                />
              ))
            )}
            {(
              (typedShow.results.deposit != null && typedShow.results.deposit > 0) ||
              (typedShow.results.withholdingAmount != null && typedShow.results.withholdingAmount > 0) ||
              (typedShow.results.totalBuyouts != null && typedShow.results.totalBuyouts > 0 && typedShow.inputs.buyoutMode !== 'show_expense')
            ) && (
              <>
                {typedShow.results.deposit != null && typedShow.results.deposit > 0 && (
                  <BreakdownList.Row
                    label="Deposit Paid"
                    value={`−${formatCurrency(typedShow.results.deposit)}`}
                    variant="negative"
                  />
                )}
                <BreakdownList.Row
                  label={typedShow.results.balanceDue != null && typedShow.results.balanceDue < 0
                    ? "Overpayment (due back to promoter)"
                    : "Balance Due at Settlement"}
                  value={formatCurrency(Math.abs(typedShow.results.balanceDue ?? 0))}
                  variant={typedShow.results.balanceDue != null && typedShow.results.balanceDue < 0 ? "warning" : "success"}
                />
              </>
            )}
            {typedShow.results.ccFees != null && typedShow.results.ccFees > 0 && typedShow.inputs.ccFeeMode !== 'off_top' && (
              <BreakdownList.Row
                label={`CC Processing Fees (${typedShow.inputs.ccFeeRate}%, venue cost)`}
                value={`−${formatCurrency(typedShow.results.ccFees)}`}
                variant="negative"
              />
            )}
            <BreakdownList.Row
              label={typedShow.results.venuePayout < 0 ? "Venue Loss" : "Promoter/House Settlement"}
              value={`${typedShow.results.venuePayout < 0 ? '−' : ''}${formatCurrency(Math.abs(typedShow.results.venuePayout))}`}
              variant={typedShow.results.venuePayout < 0 ? "warning" : "warning"}
            />
          </BreakdownList>
        </section>

        {typedShow.results.merchGross != null && typedShow.results.merchGross > 0 && (
          <section className="settlement-section">
            <h2 className="ds-section-title">Merch Settlement</h2>
            <BreakdownList>
              <BreakdownList.Row
                label="Gross Merch Sales"
                value={formatCurrency(typedShow.results.merchGross)}
              />
              <BreakdownList.Row
                label={`Venue Merch Cut (${typedShow.inputs.merchVenuePercent || '0'}%)`}
                value={`−${formatCurrency(typedShow.results.merchVenueCut ?? 0)}`}
                variant="negative"
              />
              <BreakdownList.Row
                label="Net Merch to Artist"
                value={formatCurrency(typedShow.results.merchNetToArtist ?? 0)}
                variant="success"
              />
            </BreakdownList>
          </section>
        )}

        {typedShow.results.totalDueToArtist != null && (
          <section className="settlement-section">
            <h2 className="ds-section-title">Total</h2>
            <BreakdownList>
              <BreakdownList.Row
                label="Show Balance Due"
                value={formatCurrency(
                  typedShow.results.deposit != null && typedShow.results.deposit > 0
                    ? (typedShow.results.balanceDue ?? typedShow.results.artistPayout)
                    : typedShow.results.artistPayout
                )}
              />
              <BreakdownList.Row
                label="Net Merch to Artist"
                value={formatCurrency(typedShow.results.merchNetToArtist ?? 0)}
              />
              <BreakdownList.Row
                label="Total Due to Artist"
                value={formatCurrency(typedShow.results.totalDueToArtist)}
                variant="success"
              />
            </BreakdownList>
          </section>
        )}

        {/* Footer */}
        <footer className="ds-card-footer">
          <p className="ds-card-footer-text">
            {typedShow.results.calculatedAt && (
              <>Calculated {new Date(typedShow.results.calculatedAt).toLocaleString()} · </>
            )}
            Generated via{" "}
            <Link href="/" className="ds-card-footer-link">
              Show Settlement Calculator
            </Link>
          </p>
          <p className="ds-card-footer-note">
            This is a shared settlement report. Sign up to create your own settlements.
          </p>
        </footer>
      </Card>
      </main>
    </MarketingShell>
  );
}
